apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: starter-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
      - name: starter
        image: juliaaano/java-starter:1.0.0
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        emptyDir: {}
